# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu2cg-sbva484-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Projects/frame/frame.cache/wt [current_project]
set_property parent.project_path D:/Projects/frame/frame.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Projects/frame/frame.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Projects/frame/frame.srcs/sources_1/new/data_inI.coe
add_files D:/Projects/frame/frame.srcs/sources_1/new/data_inQ.coe
add_files D:/Projects/frame/frame.srcs/sources_1/ip/text_ram/data_inI.coe
add_files D:/Projects/frame/frame.srcs/sources_1/ip/text_ramQ/data_inQ.coe
read_verilog -library xil_defaultlib {
  D:/Projects/frame/frame.srcs/sources_1/new/Frame_det_top.v
  D:/Projects/frame/frame.srcs/sources_1/new/Track.v
  D:/Projects/frame/frame.srcs/sources_1/new/Xcorr.v
  D:/Projects/frame/frame.srcs/sources_1/new/Top.v
}
read_ip -quiet D:/Projects/frame/frame.srcs/sources_1/ip/Xcorr_ram/Xcorr_ram.xci
set_property used_in_implementation false [get_files -all d:/Projects/frame/frame.srcs/sources_1/ip/Xcorr_ram/Xcorr_ram_ooc.xdc]

read_ip -quiet D:/Projects/frame/frame.srcs/sources_1/ip/Cmult_xcorr/Cmult_xcorr.xci
set_property used_in_implementation false [get_files -all d:/Projects/frame/frame.srcs/sources_1/ip/Cmult_xcorr/Cmult_xcorr_ooc.xdc]

read_ip -quiet D:/Projects/frame/frame.srcs/sources_1/ip/Xcorr_2525mult/Xcorr_2525mult.xci
set_property used_in_implementation false [get_files -all d:/Projects/frame/frame.srcs/sources_1/ip/Xcorr_2525mult/Xcorr_2525mult_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xczu2cg-sbva484-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
