# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Projects/frame/frame.srcs/sources_1/ip/Xcorr_2525mult/Xcorr_2525mult.xci
# IP: The module: 'Xcorr_2525mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/frame/frame.srcs/sources_1/ip/Xcorr_2525mult/Xcorr_2525mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Xcorr_2525mult'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Projects/frame/frame.srcs/sources_1/ip/Xcorr_2525mult/Xcorr_2525mult.xci
# IP: The module: 'Xcorr_2525mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/frame/frame.srcs/sources_1/ip/Xcorr_2525mult/Xcorr_2525mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Xcorr_2525mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
